import { EB_Garamond, Oswald } from 'next/font/google';
import './globals.css';
import PageHeader from '@/components/global/PageHeader';
import WebsiteFooter from '@/components/global/WebsiteFooter';
import Loader from '@/components/global/Loader';

// const workSans = Work_Sans({
//     variable: '--font-work-sans',
//     subsets: ['latin'],
//     weight: ['400', '500', '700'], // explicitly define weights used in project
//     display: 'swap',
// });

const oswald = Oswald({
    variable: '--font-oswald',
    subsets: ['latin'],
    weight: ['400', '700'], // only bold
    display: 'swap',
});

const ebGaramond = EB_Garamond({
    variable: '--font-eb-garamond',
    subsets: ['latin'],
    weight: ['400', '700'],
    display: 'swap',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};


export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${oswald.variable} ${ebGaramond.variable}`}>
			<head>
				<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png" />
				<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png" />
				<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png" />
				<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png" />
				<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png" />
				<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png" />
				<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png" />
				<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png" />
				<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png" />
				<link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png" />
				<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
				<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png" />
				<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
				<link rel="manifest" href="/manifest.json" />
				<meta name="msapplication-TileColor" content="#F3F5FB" />
				<meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
				<meta name="theme-color" content="#F3F5FB" />
			</head>
            <body className="antialiased relative">
				<Loader />
				<div className="bg-noise w-full overflow-hidden">
					<div className="book-lines w-full h-full">
						<section className="container overflow-hidden mx-auto">
							<PageHeader />
						</section>
					</div>
				</div>
                {children}
				<WebsiteFooter />
            </body>
        </html>
    );
}
