import { EB_Garamond, Oswald } from 'next/font/google';
import './globals.css';
import PageHeader from '@/components/global/PageHeader';

// const workSans = Work_Sans({
//     variable: '--font-work-sans',
//     subsets: ['latin'],
//     weight: ['400', '500', '700'], // explicitly define weights used in project
//     display: 'swap',
// });

const oswald = Oswald({
    variable: '--font-oswald',
    subsets: ['latin'],
    weight: '700', // only bold
    display: 'swap',
});

const ebGaramond = EB_Garamond({
    variable: '--font-eb-garamond',
    subsets: ['latin'],
    weight: ['400', '700'],
    display: 'swap',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${oswald.variable} ${ebGaramond.variable}`}>
            <body className="antialiased relative">
                {/* background with noise */}
                <div className="bg-noise w-full">
                    {/* background with lines */}
                    <div className="book-lines w-full">
                        <section className="container overflow-hidden mx-auto">
                            <PageHeader />
                        </section>
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
